name: "Tests"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '26 10 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.5'

    - name: Vet
      run: go vet -race ./pkg/ecobee

    - name: Run Tests
      run: go test -v ./pkg/ecobee
      env:
        INFLUXDB_URI: "https://us-west-2-1.aws.cloud2.influxdata.com"
        INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
        INFLUXDB_BUCKET: "ecobee-ci"
        INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG_NAME }}

    #- name: Build
    #  run: go build -o main ./
    #  env:
    #    GOOS: linux 
    #    GOARCH: amd64
    #    CGO_ENABLED: 0